def get_spell(name: str):
    return spells.get(name)


def all_spells():
    return spells

spell_template = {
    "": {
        "name": "",
        "mp_cost": 0,
        "mp_cost_percent": 0,
        "enemy_dmg": 0,
        "heal_amount": 0,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 0,
        "cooldown": 0,
        "range": 0,
        "aoe_radius": 0,
        "accuracy": 0,
        "projectile_speed": 0,
        "damage_type": "",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 0
        },
}

spells = {
    "fireball": {
        "name": "Fire Ball",
        "mp_cost": 5,
        "mp_cost_percent": 0,
        "enemy_dmg": 24,
        "heal_amount": 0,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 1.1,
        "cooldown": 2.4,
        "range": 300,
        "aoe_radius": 45,
        "accuracy": 0.86,
        "projectile_speed": 8,
        "damage_type": "fire",
        "burn_chance": 0.3,
        "burn_duration": 3,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 0
    },

    "ice_shard": {
        "name": "Ice Shard",
        "mp_cost": 6,
        "mp_cost_percent": 0,
        "enemy_dmg": 18,
        "heal_amount": 0,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 1.0,
        "cooldown": 2.0,
        "range": 280,
        "aoe_radius": 0,
        "accuracy": 0.9,
        "projectile_speed": 10,
        "damage_type": "ice",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 0.45,
        "slow_duration": 2.5,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 0
    },

    "lightning_bolt": {
        "name": "Lightning Bolt",
        "mp_cost": 8,
        "mp_cost_percent": 0,
        "enemy_dmg": 32,
        "heal_amount": 0,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 1.4,
        "cooldown": 3.0,
        "range": 350,
        "aoe_radius": 0,
        "accuracy": 0.82,
        "projectile_speed": 14,
        "damage_type": "electric",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0.28,
        "stun_duration": 1.0,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 0
    },

    "poison_dart": {
        "name": "Poison Dart",
        "mp_cost": 4,
        "mp_cost_percent": 0,
        "enemy_dmg": 9,
        "heal_amount": 0,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 0.75,
        "cooldown": 1.5,
        "range": 320,
        "aoe_radius": 0,
        "accuracy": 0.95,
        "projectile_speed": 12,
        "damage_type": "poison",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "poison_damage": 6,
        "poison_duration": 4,
        "self_damage": 0
    },

    "arcane_blast": {
        "name": "Arcane Blast",
        "mp_cost": 10,
        "mp_cost_percent": 0,
        "enemy_dmg": 38,
        "heal_amount": 0,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 1.9,
        "cooldown": 4.0,
        "range": 250,
        "aoe_radius": 60,
        "accuracy": 0.76,
        "projectile_speed": 6,
        "damage_type": "arcane",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 0
    },

    "heal": {
        "name": "Heal",
        "mp_cost": 6,
        "mp_cost_percent": 0,
        "enemy_dmg": 0,
        "heal_amount": 27,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 1.4,
        "cooldown": 3.0,
        "range": 0,
        "aoe_radius": 0,
        "accuracy": 1.0,
        "projectile_speed": 0,
        "damage_type": "holy",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 0
    },

    "meteor": {
        "name": "Meteor",
        "mp_cost": 15,
        "mp_cost_percent": 0,
        "enemy_dmg": 60,
        "heal_amount": 0,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 3.1,
        "cooldown": 6.5,
        "range": 400,
        "aoe_radius": 100,
        "accuracy": 0.72,
        "projectile_speed": 4,
        "damage_type": "fire",
        "burn_chance": 0.65,
        "burn_duration": 5,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 0
    },

    "wind_slash": {
        "name": "Wind Slash",
        "mp_cost": 5,
        "mp_cost_percent": 0,
        "enemy_dmg": 17,
        "heal_amount": 0,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 0.55,
        "cooldown": 1.7,
        "range": 260,
        "aoe_radius": 0,
        "accuracy": 0.91,
        "projectile_speed": 16,
        "damage_type": "wind",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 14,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 0
    },

    "earth_spike": {
        "name": "Earth Spike",
        "mp_cost": 7,
        "mp_cost_percent": 0,
        "enemy_dmg": 26,
        "heal_amount": 0,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 1.7,
        "cooldown": 3.5,
        "range": 240,
        "aoe_radius": 35,
        "accuracy": 0.8,
        "projectile_speed": 5,
        "damage_type": "earth",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0.22,
        "stun_duration": 1,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 0
    },

    "shadow_bolt": {
        "name": "Shadow Bolt",
        "mp_cost": 9,
        "mp_cost_percent": 0,
        "enemy_dmg": 36,
        "heal_amount": 0,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 1.25,
        "cooldown": 3.0,
        "range": 330,
        "aoe_radius": 0,
        "accuracy": 0.86,
        "projectile_speed": 11,
        "damage_type": "dark",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0.22,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 0
    },

    "holy_light": {
        "name": "Holy Light",
        "mp_cost": 10,
        "mp_cost_percent": 0,
        "enemy_dmg": 18,
        "heal_amount": 22,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 1.9,
        "cooldown": 4.0,
        "range": 300,
        "aoe_radius": 50,
        "accuracy": 0.82,
        "projectile_speed": 7,
        "damage_type": "holy",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 0
    },

    "chain_lightning": {
        "name": "Chain Lightning",
        "mp_cost": 12,
        "mp_cost_percent": 0,
        "enemy_dmg": 23,
        "heal_amount": 0,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 1.5,
        "cooldown": 4.5,
        "range": 340,
        "aoe_radius": 0,
        "accuracy": 0.9,
        "projectile_speed": 13,
        "damage_type": "electric",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 3,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 0
    },

    "blood_pact": {
        "name": "Blood Pact",
        "mp_cost": 0,
        "mp_cost_percent": 0,
        "enemy_dmg": 48,
        "heal_amount": 0,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 2.4,
        "cooldown": 6.0,
        "range": 280,
        "aoe_radius": 0,
        "accuracy": 0.76,
        "projectile_speed": 6,
        "damage_type": "blood",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 14
    },

    "frost_nova": {
        "name": "Frost Nova",
        "mp_cost": 11,
        "mp_cost_percent": 0,
        "enemy_dmg": 14,
        "heal_amount": 0,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 1.3,
        "cooldown": 5.0,
        "range": 0,
        "aoe_radius": 120,
        "accuracy": 1.0,
        "projectile_speed": 0,
        "damage_type": "ice",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 1.0,
        "slow_duration": 3,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 0
    },

    "inferno_pulse": {
        "name": "Inferno Pulse",
        "mp_cost": 14,
        "mp_cost_percent": 0,
        "enemy_dmg": 52,
        "heal_amount": 0,
        "mp_scaling_damage": 0,
        "scaling_type": "",
        "cast_time": 2.1,
        "cooldown": 5.5,
        "range": 260,
        "aoe_radius": 80,
        "accuracy": 0.8,
        "projectile_speed": 5,
        "damage_type": "fire",
        "burn_chance": 0.55,
        "burn_duration": 4,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 5
    },

    "heavenly_judgment": {
        "name": "Heavenly Judgment",
        "mp_cost": 0,
        "mp_cost_percent": 75,
        "enemy_dmg": 0,
        "enemy_dmg_base": 65,
        "heal_amount": 0,
        "mp_scaling_damage": 4.5,
        "scaling_type": "mana_to_damage",
        "cast_time": 2.8,
        "cooldown": 8.0,
        "range": 300,
        "aoe_radius": 120,
        "accuracy": 0.93,
        "projectile_speed": 6,
        "damage_type": "holy",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 0,
        "slow_duration": 0,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0,
        "chain_targets": 0,
        "purge_chance": 0.6,
        "purge_duration": 5,
        "self_damage": 0
    },

    "blood_drain": {
        "name": "Blood Drain",
        "mp_cost": 25,
        "mp_cost_percent": 0,
        "enemy_dmg": 40,
        "heal_amount": 0,
        "mp_scaling_damage": 0.2,
        "scaling_type": "magic",
        "cast_time": 1.2,
        "cooldown": 6,
        "range": 5,
        "aoe_radius": 0,
        "accuracy": 95,
        "projectile_speed": 0,
        "damage_type": "blood",
        "burn_chance": 0,
        "burn_duration": 0,
        "slow_chance": 20,
        "slow_duration": 2,
        "stun_chance": 0,
        "stun_duration": 0,
        "knockback": 0,
        "lifesteal": 0.5,
        "chain_targets": 0,
        "purge_chance": 0,
        "purge_duration": 0,
        "self_damage": 0
    }
}