import sys, os

parent_dir = os.path.abspath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
)
sys.path.append(parent_dir)

from init import *


class SeedArcive:
    seeds = {
        "Peashooter": {
            "cost": 100,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 20,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Sunflower": {
            "cost": 50,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "production",
            "is_mushroom": False,
        },
        "Cherry Bomb": {
            "cost": 150,
            "recharge_seconds": 35.0,
            "toughness": 300,
            "damage_per_hit": 1800,
            "aoe_range": 3.0,
            "type": "explosive",
            "is_mushroom": False,
        },
        "Wall-nut": {
            "cost": 50,
            "recharge_seconds": 30.0,
            "toughness": 4000,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "defensive",
            "is_mushroom": False,
        },
        "Potato Mine": {
            "cost": 25,
            "recharge_seconds": 30.0,
            "toughness": 300,
            "damage_per_hit": 1800,
            "aoe_range": 1.0,
            "type": "explosive",
            "is_mushroom": False,
        },
        "Snow Pea": {
            "cost": 175,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 20,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Chomper": {
            "cost": 150,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 1800,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Repeater": {
            "cost": 200,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 40,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Puff-shroom": {
            "cost": 0,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 20,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": True,
        },
        "Sun-shroom": {
            "cost": 25,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "production",
            "is_mushroom": True,
        },
        "Fume-shroom": {
            "cost": 75,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 20,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": True,
        },
        "Grave Buster": {
            "cost": 75,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "environmental",
            "is_mushroom": False,
        },
        "Hypno-shroom": {
            "cost": 75,
            "recharge_seconds": 30.0,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "charm",
            "is_mushroom": True,
        },
        "Scaredy-shroom": {
            "cost": 25,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 20,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": True,
        },
        "Ice-shroom": {
            "cost": 75,
            "recharge_seconds": 50.0,
            "toughness": 300,
            "damage_per_hit": 20,
            "aoe_range": 9.0,
            "type": "offensive",
            "is_mushroom": True,
        },
        "Doom-shroom": {
            "cost": 125,
            "recharge_seconds": 50.0,
            "toughness": 300,
            "damage_per_hit": 1800,
            "aoe_range": 7.0,
            "type": "explosive",
            "is_mushroom": True,
        },
        "Lily Pad": {
            "cost": 25,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "environmental",
            "is_mushroom": False,
        },
        "Squash": {
            "cost": 50,
            "recharge_seconds": 30.0,
            "toughness": 300,
            "damage_per_hit": 1800,
            "aoe_range": 1.0,
            "type": "explosive",
            "is_mushroom": False,
        },
        "Threepeater": {
            "cost": 325,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 20,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Tangle Kelp": {
            "cost": 25,
            "recharge_seconds": 30.0,
            "toughness": 300,
            "damage_per_hit": 1800,
            "aoe_range": 0.0,
            "type": "explosive",
            "is_mushroom": False,
        },
        "Jalapeno": {
            "cost": 125,
            "recharge_seconds": 50.0,
            "toughness": 300,
            "damage_per_hit": 1800,
            "aoe_range": 9.0,
            "type": "explosive",
            "is_mushroom": False,
        },
        "Spikeweed": {
            "cost": 100,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 11,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Torchwood": {
            "cost": 175,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "buff",
            "is_mushroom": False,
        },
        "Tall-nut": {
            "cost": 125,
            "recharge_seconds": 30.0,
            "toughness": 8000,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "defensive",
            "is_mushroom": False,
        },
        "Sea-shroom": {
            "cost": 0,
            "recharge_seconds": 30.0,
            "toughness": 300,
            "damage_per_hit": 20,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": True,
        },
        "Plantern": {
            "cost": 25,
            "recharge_seconds": 30.0,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 3.0,
            "type": "environmental",
            "is_mushroom": False,
        },
        "Cactus": {
            "cost": 125,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 20,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Blover": {
            "cost": 100,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 9.0,
            "type": "environmental",
            "is_mushroom": False,
        },
        "Split Pea": {
            "cost": 125,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 20,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Starfruit": {
            "cost": 125,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 20,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Pumpkin": {
            "cost": 125,
            "recharge_seconds": 30.0,
            "toughness": 4000,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "defensive",
            "is_mushroom": False,
        },
        "Magnet-shroom": {
            "cost": 100,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 3.5,
            "type": "disarm",
            "is_mushroom": True,
        },
        "Cabbage-pult": {
            "cost": 100,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 40,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Flower Pot": {
            "cost": 25,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "environmental",
            "is_mushroom": False,
        },
        "Kernel-pult": {
            "cost": 100,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 20,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Coffee Bean": {
            "cost": 75,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "buff",
            "is_mushroom": False,
        },
        "Garlic": {
            "cost": 50,
            "recharge_seconds": 7.5,
            "toughness": 2400,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "defensive",
            "is_mushroom": False,
        },
        "Marigold": {
            "cost": 50,
            "recharge_seconds": 30.0,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "production",
            "is_mushroom": False,
        },
        "Melon-pult": {
            "cost": 300,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 80,
            "aoe_range": 3.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Umbrella Leaf": {
            "cost": 50,
            "recharge_seconds": 7.5,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 3.0,
            "type": "defensive",
            "is_mushroom": False,
        },
        "Gatling Pea": {
            "cost": 250,
            "recharge_seconds": 50.0,
            "toughness": 300,
            "damage_per_hit": 80,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Twin Sunflower": {
            "cost": 150,
            "recharge_seconds": 50.0,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "production",
            "is_mushroom": False,
        },
        "Gloom-shroom": {
            "cost": 150,
            "recharge_seconds": 50.0,
            "toughness": 300,
            "damage_per_hit": 80,
            "aoe_range": 1.5,
            "type": "offensive",
            "is_mushroom": True,
        },
        "Cattail": {
            "cost": 225,
            "recharge_seconds": 50.0,
            "toughness": 300,
            "damage_per_hit": 20,
            "aoe_range": 9.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Winter Melon": {
            "cost": 200,
            "recharge_seconds": 50.0,
            "toughness": 300,
            "damage_per_hit": 80,
            "aoe_range": 3.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Spikerock": {
            "cost": 125,
            "recharge_seconds": 50.0,
            "toughness": 9,
            "damage_per_hit": 22,
            "aoe_range": 0.0,
            "type": "offensive",
            "is_mushroom": False,
        },
        "Cob Cannon": {
            "cost": 500,
            "recharge_seconds": 30.0,
            "toughness": 300,
            "damage_per_hit": 1800,
            "aoe_range": 3.0,
            "type": "explosive",
            "is_mushroom": False,
        },
        "Imitater": {
            "cost": 0,
            "recharge_seconds": 30.0,
            "toughness": 300,
            "damage_per_hit": 0,
            "aoe_range": 0.0,
            "type": "environmental",
            "is_mushroom": False,
        },
    }

    def get_all(self):
        return self.seeds
